### ISSUE TITLE
What does your dev environment look like?

### ISSUE THREAD

**Issue by sindresorhus** [ChristopherBiscardi/ama#3]
Editor, terminal, tools, themes, fonts, process, etc.

**Comment by ChristopherBiscardi** [comment]
# Editor

[emacs in a container](https://github.com/ChristopherBiscardi/docker-emacs)

# Terminal

[iTerm2](https://www.iterm2.com/) with [oh my zsh](https://github.com/robbyrussell/oh-my-zsh) ([.zshrc](https://github.com/ChristopherBiscardi/dotfiles/blob/master/bak.zshrc)) 
![screenshot 2015-10-03 13 25 28](https://cloud.githubusercontent.com/assets/551247/10264964/4365d6da-69d2-11e5-8a1e-36c49d6f7fb8.png)

# Tools

## source control

git

## chat
-  [weechat](https://weechat.org/)
- slack (reactiflux, dist-sys, some other channels)

## dev-tools
- docker
- docker-machine
- docker-compose

## node
- nvm
- eslint
- babel
- webpack

## css
- PostCSS
- css-modules

## haskell
- ghc-mod
- [haskell-mode](https://github.com/haskell/haskell-mode)

## static sites

[gatsby](https://github.com/gatsbyjs/gatsby)

## gifs

[licecap](http://www.cockos.com/licecap/)

# fonts

[Meslo LG Powerline](https://github.com/powerline/fonts/tree/master/Meslo)
