### ISSUE TITLE
What's your favorite gif?

### ISSUE THREAD

**Issue by sindresorhus** [ChristopherBiscardi/ama#5]

**Comment by ChristopherBiscardi** [comment]
![left_shark](https://cloud.githubusercontent.com/assets/551247/10559990/bddef07e-74b1-11e5-8106-b791811235f4.gif)![left_shark](https://cloud.githubusercontent.com/assets/551247/10559990/bddef07e-74b1-11e5-8106-b791811235f4.gif)![left_shark](https://cloud.githubusercontent.com/assets/551247/10559990/bddef07e-74b1-11e5-8106-b791811235f4.gif)![left_shark](https://cloud.githubusercontent.com/assets/551247/10559990/bddef07e-74b1-11e5-8106-b791811235f4.gif)![left_shark](https://cloud.githubusercontent.com/assets/551247/10559990/bddef07e-74b1-11e5-8106-b791811235f4.gif)![left_shark](https://cloud.githubusercontent.com/assets/551247/10559990/bddef07e-74b1-11e5-8106-b791811235f4.gif)![left_shark](https://cloud.githubusercontent.com/assets/551247/10559990/bddef07e-74b1-11e5-8106-b791811235f4.gif)![left_shark](https://cloud.githubusercontent.com/assets/551247/10559990/bddef07e-74b1-11e5-8106-b791811235f4.gif)![left_shark](https://cloud.githubusercontent.com/assets/551247/10559990/bddef07e-74b1-11e5-8106-b791811235f4.gif)![left_shark](https://cloud.githubusercontent.com/assets/551247/10559990/bddef07e-74b1-11e5-8106-b791811235f4.gif)![left_shark](https://cloud.githubusercontent.com/assets/551247/10559990/bddef07e-74b1-11e5-8106-b791811235f4.gif)![left_shark](https://cloud.githubusercontent.com/assets/551247/10559990/bddef07e-74b1-11e5-8106-b791811235f4.gif)![left_shark](https://cloud.githubusercontent.com/assets/551247/10559990/bddef07e-74b1-11e5-8106-b791811235f4.gif)![left_shark](https://cloud.githubusercontent.com/assets/551247/10559990/bddef07e-74b1-11e5-8106-b791811235f4.gif)![left_shark](https://cloud.githubusercontent.com/assets/551247/10559990/bddef07e-74b1-11e5-8106-b791811235f4.gif)![left_shark](https://cloud.githubusercontent.com/assets/551247/10559990/bddef07e-74b1-11e5-8106-b791811235f4.gif)![left_shark](https://cloud.githubusercontent.com/assets/551247/10559990/bddef07e-74b1-11e5-8106-b791811235f4.gif)![left_shark](https://cloud.githubusercontent.com/assets/551247/10559990/bddef07e-74b1-11e5-8106-b791811235f4.gif)![left_shark](https://cloud.githubusercontent.com/assets/551247/10559990/bddef07e-74b1-11e5-8106-b791811235f4.gif)![left_shark](https://cloud.githubusercontent.com/assets/551247/10559990/bddef07e-74b1-11e5-8106-b791811235f4.gif)
